In [62]:
import numpy as np

In [63]:
a = np.array([19, 13])[:,np.newaxis]
b = np.array([18, 19])[:,np.newaxis]

a1 = np.array([-2,  1])[:,np.newaxis]
b1 = np.array([-1, -1])[:,np.newaxis]

# trin 1 : vis ikke, parralelle
np.vdot(a1,b1) / (np.linalg.norm(a1) * np.linalg.norm(b1))

0.31622776601683794

$$

a_1 + t_1 * b_1 = a_2 + t_2 *b_2 \\
a_1 - a_2 = t_2 *b_2 - t_1 * b_1 \\

a_1 - a_2 = [-b_1, b_2]\begin{bmatrix} t_1 \\ t_2  \end{bmatrix}


$$

In [64]:
# Opsæt A og som følgdende B*t=a 

A = a-b
B = np.hstack([-a1,b1])
t= np.linalg.inv(B) @A
t

array([[2.33333333],
       [3.66666667]])

In [65]:
a + t[0]*a1

array([[14.33333333],
       [15.33333333]])

In [66]:
b + t[1]*b1

array([[14.33333333],
       [15.33333333]])

119566840879742, 430566433235378, 268387686114969 @ 18, -130, 74
433973471892198, 260061119249300, 263051300077633 @ -16, -170, -118
44446443386018, 281342848485672, 166638492241385 @ 197, 16, 200
102165762267068, 293235409083300, 334966976680379 @ 19, 15, 9

$$

a+av*t_1 = s + sv * t_1 \\
b+bv*t_2 = s + sv * t_2\\
c+cv*t_3 = s + sv * t_3

$$

import sym

In [77]:
import sympy as sp

x = sp.symbols("x")
y = sp.symbols("y")
z = sp.symbols("z")
vx, vy, vz = sp.symbols("vx vy vz")
t1, t2, t3, t4 = sp.symbols("t1 t2 t3, t4")

a = sp.solve([
        119566840879742 + 18 * t1 - (x + vx * t1),
        430566433235378 - 130 * t1 - (y + vy * t1),
        268387686114969 + 74 * t1 - (z + vz * t1),
        433973471892198 - 16 * t2 - (x + vx * t2),
        260061119249300 - 170 * t2 - (y + vy * t2),
        263051300077633 - 118 * t2  -(z + vz * t2),
        44446443386018 + 197 * t3 - (x + vx * t3),
        281342848485672 + 16 * t3 - (y + vy * t3),
        166638492241385 + 200 * t3 - (z + vz * t3),

])
a

[{t1: 962702686958,
  t2: 65649375952,
  t3: 778256039004,
  vx: -330,
  vy: 63,
  vz: 94,
  x: 454587375941126,
  y: 244764814652484,
  z: 249133632375809}]

In [78]:
454587375941126 +244764814652484 +249133632375809

948485822969419

In [38]:
sp.solve([x-2, y+x])

{x: 2, y: -2}